
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zakia
 */
public class Newmember extends javax.swing.JFrame {

    /**
     * Creates new form Newmember
     */
    public Newmember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleThreeTextfield = new javax.swing.JTextField();
        birthdateTextfield = new javax.swing.JTextField();
        iDNewMembTextField = new javax.swing.JTextField();
        emailTextfield = new javax.swing.JTextField();
        RoleLabel = new javax.swing.JLabel();
        birthdateLabel = new javax.swing.JLabel();
        iDLabel = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        saveNewMembButton = new javax.swing.JButton();
        memberSinceTextfield = new javax.swing.JTextField();
        memberSinceLabel = new javax.swing.JLabel();
        playerCoachParentLabel = new javax.swing.JLabel();
        TeamLabel = new javax.swing.JLabel();
        nameNewMembTextField = new javax.swing.JTextField();
        roleTwoTextfield = new javax.swing.JTextField();
        roleOneTextfield = new javax.swing.JTextField();
        teamTwoTextfield = new javax.swing.JTextField();
        teamThreeTextfield = new javax.swing.JTextField();
        TeamOneTextfield = new javax.swing.JTextField();
        nameLabel2 = new javax.swing.JLabel();
        TeamLabel1 = new javax.swing.JLabel();
        TeamLabel2 = new javax.swing.JLabel();
        TeamLabel3 = new javax.swing.JLabel();
        surnameLabel1 = new javax.swing.JLabel();
        surnameNewMembTextfield = new javax.swing.JTextField();
        birthdateLabel1 = new javax.swing.JLabel();
        activeTextfield = new javax.swing.JTextField();
        birthdateLabel2 = new javax.swing.JLabel();
        teamLabel2 = new javax.swing.JLabel();
        genderTextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roleThreeTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleThreeTextfieldActionPerformed(evt);
            }
        });

        birthdateTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateTextfieldActionPerformed(evt);
            }
        });

        iDNewMembTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iDNewMembTextFieldActionPerformed(evt);
            }
        });

        emailTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextfieldActionPerformed(evt);
            }
        });

        RoleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RoleLabel.setText("Roll:");

        birthdateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        birthdateLabel.setText("Födelsedatum:");

        iDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iDLabel.setText("ID:");

        teamLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teamLabel.setText("E-mail:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Skapa ny  medlem");

        returnButton.setText("Tillbaka");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        saveNewMembButton.setText(" Spara ny medlem");
        saveNewMembButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewMembButtonActionPerformed(evt);
            }
        });

        memberSinceTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberSinceTextfieldActionPerformed(evt);
            }
        });

        memberSinceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memberSinceLabel.setText("Member since:");

        playerCoachParentLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        playerCoachParentLabel.setText("0=Spelare, 1=Coach, 2=Förälder");

        TeamLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TeamLabel.setText("2");

        nameNewMembTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameNewMembTextFieldActionPerformed(evt);
            }
        });

        roleTwoTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleTwoTextfieldActionPerformed(evt);
            }
        });

        roleOneTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleOneTextfieldActionPerformed(evt);
            }
        });

        teamTwoTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamTwoTextfieldActionPerformed(evt);
            }
        });

        teamThreeTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamThreeTextfieldActionPerformed(evt);
            }
        });

        TeamOneTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamOneTextfieldActionPerformed(evt);
            }
        });

        nameLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel2.setText("Namn:");

        TeamLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TeamLabel1.setText("Team:");

        TeamLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TeamLabel2.setText("1");

        TeamLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TeamLabel3.setText("3");

        surnameLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surnameLabel1.setText("Efternamn:");

        birthdateLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        birthdateLabel1.setText(" Inaktiv:0, Aktiv:1");

        activeTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeTextfieldActionPerformed(evt);
            }
        });

        birthdateLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        birthdateLabel2.setText("Aktiv:");

        teamLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teamLabel2.setText("Kön:");

        genderTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameNewMembTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(memberSinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(memberSinceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(teamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(iDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(surnameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(teamLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(birthdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(iDNewMembTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(surnameNewMembTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(genderTextfield))
                                    .addComponent(birthdateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(birthdateLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(birthdateLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeamLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeamLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TeamLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(teamTwoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(roleTwoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(TeamOneTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RoleLabel)
                                            .addComponent(roleOneTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(returnButton)
                                            .addComponent(teamThreeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(roleThreeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(saveNewMembButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(playerCoachParentLabel)
                                .addGap(21, 21, 21))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeamLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameNewMembTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameNewMembTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerCoachParentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthdateLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(activeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdateLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeamOneTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleOneTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeamLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iDNewMembTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teamTwoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleTwoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleThreeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamThreeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeamLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveNewMembButton)
                            .addComponent(returnButton))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teamLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(memberSinceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(memberSinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))))
        );

        saveNewMembButton.getAccessibleContext().setAccessibleName("Create New Member");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iDNewMembTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iDNewMembTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iDNewMembTextFieldActionPerformed

    private void emailTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextfieldActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
            setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    private void saveNewMembButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewMembButtonActionPerformed
        // TODO add your handling code here:
        
        String name;
        String familyName;
        String birthdate;
        String active;
        String id;
        String team;
        String email;
        String gender;
        String memberSince;
        String team1;
        String team2;
        String team3;
        String role1;
        String role2;
        String role3;
        
        
        name=nameNewMembTextField.getText();
        familyName=surnameNewMembTextfield.getText();
        birthdate=birthdateTextfield.getText();
        active=activeTextfield.getText();
        id=iDNewMembTextField.getText();
        email=emailTextfield.getText();
        gender=genderTextfield.getText();
        memberSince=memberSinceTextfield.getText();
        team1=TeamOneTextfield.getText();
        team2=teamTwoTextfield.getText();
        team3=teamThreeTextfield.getText();
        role1=roleOneTextfield.getText();
        role2=roleTwoTextfield.getText();
        role3=roleThreeTextfield.getText();        
        
        if ( name.equals("")|| familyName.equals("") || birthdate.equals("") || active.equals("") || id.equals("") || email.equals("")||gender.equals("") || memberSince.equals("")) {
        JOptionPane.showMessageDialog(null,"OBS!Alla fält  måste fyllas i!");
    } 
        else if (( team1.equals ("") && team2.equals ("") && team3.equals ("") && role1.equals ("") &&  role2.equals ("") && role3.equals ("") ) 
            || (team1.equals("") && !role1.equals("") ) || (!team1.equals("") && role1.equals("") ) || (team2.equals("") && !role2.equals("") ) || (!team2.equals("") && role2.equals("") )
            || (!team3.equals("") && role3.equals("") ) || (team3.equals("") && !role3.equals("") ) || (!team3.equals("") && role3.equals("") )) {
        JOptionPane.showMessageDialog(null,"Minst ett lag med en roll måste vara ifylld!");
    }
            else {
                    
                    int activeInt=Integer.parseInt(active);
                    int idInt=Integer.parseInt(id);
                    int role1Int=Integer.parseInt(role1);
                    int role2Int=Integer.parseInt(role2);
                    int role3Int=Integer.parseInt(role3);
                    
                    
                    JOptionPane.showMessageDialog(null,"Medlemmen är registrerad!");
                    setVisible(false);
                    }
           
        
        
        
    }//GEN-LAST:event_saveNewMembButtonActionPerformed

    private void roleThreeTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleThreeTextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_roleThreeTextfieldActionPerformed

    private void memberSinceTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberSinceTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberSinceTextfieldActionPerformed

    private void nameNewMembTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameNewMembTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameNewMembTextFieldActionPerformed

    private void roleTwoTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleTwoTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleTwoTextfieldActionPerformed

    private void roleOneTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleOneTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleOneTextfieldActionPerformed

    private void teamTwoTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamTwoTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamTwoTextfieldActionPerformed

    private void teamThreeTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamThreeTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamThreeTextfieldActionPerformed

    private void TeamOneTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamOneTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamOneTextfieldActionPerformed

    private void birthdateTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateTextfieldActionPerformed

    private void activeTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeTextfieldActionPerformed

    private void genderTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newmember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JLabel TeamLabel;
    private javax.swing.JLabel TeamLabel1;
    private javax.swing.JLabel TeamLabel2;
    private javax.swing.JLabel TeamLabel3;
    private javax.swing.JTextField TeamOneTextfield;
    private javax.swing.JTextField activeTextfield;
    private javax.swing.JLabel birthdateLabel;
    private javax.swing.JLabel birthdateLabel1;
    private javax.swing.JLabel birthdateLabel2;
    private javax.swing.JTextField birthdateTextfield;
    private javax.swing.JTextField emailTextfield;
    private javax.swing.JTextField genderTextfield;
    private javax.swing.JLabel iDLabel;
    private javax.swing.JTextField iDNewMembTextField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel memberSinceLabel;
    private javax.swing.JTextField memberSinceTextfield;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JTextField nameNewMembTextField;
    private javax.swing.JLabel playerCoachParentLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField roleOneTextfield;
    private javax.swing.JTextField roleThreeTextfield;
    private javax.swing.JTextField roleTwoTextfield;
    private javax.swing.JButton saveNewMembButton;
    private javax.swing.JLabel surnameLabel1;
    private javax.swing.JTextField surnameNewMembTextfield;
    private javax.swing.JLabel teamLabel;
    private javax.swing.JLabel teamLabel2;
    private javax.swing.JTextField teamThreeTextfield;
    private javax.swing.JTextField teamTwoTextfield;
    // End of variables declaration//GEN-END:variables
}
